[phases.setup]
nixPkgs = ["nodejs-18_x", "python311"]

[phases.install]
cmds = [
  "pip install -r requirements.txt",
  "cd ../frontend && npm install && npm run build",
  "mkdir -p dist && cp -r ../frontend/dist ./dist"
]

[phases.build]

[start]
cmd = "uvicorn main:app --host 0.0.0.0 --port $PORT"
